Task
arbaev/simpler pull request #1
Opened 2019-03-24 19:44 UTC by arbaev

2019-03-26 04:29 UTC, iBublik requested changes

2019-03-26 04:29 UTC, iBublik commented on lib/simpler/application.rb
> +    rescue NoMethodError => e
Это слишком общая ошибка, она может возникнуть вовсе не из-за отстуствия роута. Это верный способ ввести пользователя в ступор, ты ему будешь отдавать 404, хотя страница существует, просто у тебя в коде ошибка. Проверь что route не nil, если проверка не прошла - тогда уже возвращай 404

2019-03-26 04:29 UTC, iBublik commented on lib/simpler/application.rb
> +      make_response(Controller.new(env), :not_found)
А зачем это через контроллер прогонять? Просто сразу отдай rack совместимый ответ

2019-03-26 04:29 UTC, iBublik commented on lib/simpler/controller.rb
> +      if template.is_a?(Hash) && template.has_key?(:plain)
`has_key?` deprecated, используй `key?`/`include?`

2019-03-26 04:29 UTC, iBublik commented on lib/simpler/controller.rb
> +        set_headers(:plain)
Зачем так жестко зашиваться на то, что если в template хэш, то это обязательно plain? Просто возьми ключ, который тебе в хэше пришел, это и будет типом

2019-03-26 04:29 UTC, iBublik commented on lib/simpler/controller.rb
> +    def controller_found?
Вот эта проверка внутри контроллера выглядит очень странно :)

2019-03-26 04:29 UTC, iBublik commented on lib/simpler/controller.rb
> +    def status(number)
```suggestion
    def status(code)
```

2019-03-26 04:29 UTC, iBublik commented on lib/simpler/controller.rb
> +    def set_headers(type = :html)
Название метода путает. Кажется, что он любой заголовок может установить, а по факту только content type

2019-03-26 04:29 UTC, iBublik commented on lib/simpler/router.rb
> +    def split_path(path)
Почему этим занимается роутер, а не роут?

2019-03-26 04:29 UTC, iBublik commented on lib/simpler/router/route.rb
> +        @path, text_id = path
Ты зашиваешься на определенную структуру пути, это неправильно. Путь может состоять и из нескольких параметров, расположенных где угодно `/my/categories/:title/posts/:id`

2019-03-26 04:29 UTC, iBublik commented on lib/simpler/router/route.rb
> +          @method == method && mpath.match(@path)
```suggestion
          @method == method && mpath.match?(@path)
```

2019-03-26 04:29 UTC, iBublik commented on lib/simpler/router/route.rb
> +        mpath, value = path
Что за mpath?

2019-03-26 04:29 UTC, iBublik commented on lib/simpler/router/route.rb
> +        elsif value && @id
Не нужно гнаться за двумя зайцами. Должно быть 2 метода - 1 для проверки, что роут соответствует текущему пути, второй для получения переменных из текущего пути

2019-03-26 04:29 UTC, iBublik commented on lib/simpler/router/route.rb
> +          @param = {@id => value.to_i}
Параметр не обязательно является числом

2019-03-26 04:29 UTC, iBublik commented on lib/simpler/router/route.rb
> +          @param = {@id => value.to_i}
Идея хранить переменные маршрута в инстансе роута неверна. У тебя роут должен хранить только метаданные (то, что не меняется от запроса к запросу). Иначе ты рискуешь набить роут данными из разных запросов, и получить трудноотслеживаемую ошибку

2019-03-27 06:48 UTC, iBublik requested changes

2019-03-27 06:48 UTC, iBublik commented on lib/simpler/application.rb
> +      query_params = Rack::Utils.parse_nested_query(env['QUERY_STRING'])
По идее, все это должно быть доступно через `request.params`. А сейчас ты потерял параметры формы

2019-03-27 06:48 UTC, iBublik commented on lib/simpler/controller.rb
> +      template ? template.values.first : View.new(@request.env).render(binding)
А если тебе JSON надо отрендерить? Нельзя делать исключений, любой рендеринг должен проходить через View, иначе часть логики отоброжения протекает в контроллер.

2019-03-27 06:48 UTC, iBublik commented on lib/simpler/router/route.rb
> +        source_path_arr.reduce({}) do |params, el|
Используй `with_index` для получения индекса + `with_object` для создания хэша, удобнее будет.

2019-03-27 06:48 UTC, iBublik commented on lib/simpler/router/route.rb
> +        !!recognize_params(path)
У тебя все равно метод гонится за двумя зайцами. Общую часть можно вынести в приватный метод (тут придется вспомнить как ты работал с итераторами в курсе по ruby, вспомни задание про итерацию вагонов ) - это не обязательно, если что пускает будет дублирование.

2019-03-27 06:48 UTC, iBublik commented on lib/simpler/router/route.rb
> +          return nil if route_el.nil?
Проще изначально сравнить длины массивов, если не сходятся - значит путь не подходит

2019-03-27 15:15 UTC, iBublik requested changes

2019-03-27 15:15 UTC, iBublik commented on lib/middleware/racklogger.rb
> +    Dir.mkdir("#{Simpler.root}/#{LOG_DIRNAME}") unless Dir.exist?("#{Simpler.root}/#{LOG_DIRNAME}")
Не очень понимаю зачем это нужно, особенно в миддлваре. Директория куда пишутся логи заранее определена, значит она должна существовать на момент вызова этого кода

2019-03-27 15:15 UTC, iBublik commented on lib/middleware/racklogger.rb
> +    @data = {
В rack приложениях нельзя в call создавать инстанс-переменные. Формально можно, но так легко себе в ногу выстрелить. Миддлвара иницилизируется 1 раз, а `call` вызывается при каждом запросе. Соответственно, если ты что-то пишешь в инстанс переменную в call, то инстанс миддлвары содержит в себе данные отдельного запроса. И все это может привести к проблемам, которые я описывал [тут](https://github.com/arbaev/simpler/pull/1#discussion_r268939834)

2019-03-27 15:15 UTC, iBublik commented on lib/middleware/racklogger.rb
> +    File.open("#{Simpler.root}/#{LOG_DIRNAME}/#{LOG_FILENAME}", "a+") {|f| f.write(output) }
В Ruby есть класс Logger

2019-03-27 15:15 UTC, iBublik commented on lib/simpler/application.rb
> +    def collect_params(route, controller)
Почему сюда сразу request не передать, зачем контроллер?

2019-03-27 15:15 UTC, iBublik commented on lib/simpler/view.rb
> +        template.values.first
Я предлагал вызывать метож в зависимости от типа рендеринга. Если там plain - то render_plain, если json - render_json и т.д. Пока что достаточно реализовать render_plain, но в коде можно заложить возможность расширения

2019-03-28 16:38 UTC, iBublik requested changes

2019-03-28 16:38 UTC, iBublik commented on lib/middleware/racklogger.rb
> +    file = File.open("#{Simpler.root}/#{LOG_DIRNAME}/#{LOG_FILENAME}", "a+")
Не надо открывать файл, просто передай путь, логгер все за тебя сделает

2019-03-28 16:38 UTC, iBublik commented on lib/middleware/racklogger.rb
> +    @logger = Logger.new(file, formatter: proc {|severity, datetime, progname, msg|
Неиспользуемые параметры принято именовать с нижним подчеркиванием

2019-03-28 16:38 UTC, iBublik commented on lib/middleware/racklogger.rb
> +    @logger.close
Это не нужно делать

2019-03-28 16:38 UTC, iBublik commented on lib/middleware/racklogger.rb
> +    parameters = data[:params].nil? || data[:params].empty? ? "none" : data[:params]
Хорошей практикой считается, что если данные содержат коллекцию, то в них не должно быть nil. Вместо этого там должна быть пустая коллекция. Это позволяет избежать лишних проверок на nil

2019-03-28 16:38 UTC, iBublik commented on lib/simpler/controller.rb
> +      @response['Content-Type'] = CONTENT_TYPES[type] || 'text/unknown'
Что за `text/unknown`? Такого типа не существует. Логичнее с ошибкой свалиться, если тебе пришел неизвестный формат

2019-03-28 16:38 UTC, iBublik commented on lib/simpler/controller.rb
> +      @request.env['simpler.template'] = {}
Зачем это в конструкторе? Разве есть ситуации когда у тебя не устанавливается этот параметр?

2019-03-28 16:38 UTC, iBublik commented on lib/simpler/controller.rb
> +    rescue ArgumentError => e
Что это?

2019-03-28 16:38 UTC, iBublik commented on lib/simpler/router/route.rb
> +            return false if el != path_arr[i]
Очень тяжело читается. Рекомендую посмотреть в сторону метода `all?`

2019-03-28 16:38 UTC, iBublik commented on lib/simpler/router/route.rb
> +        result = pattern.map.with_index do |el, i|
```ruby
pattern.each.with_index.with_object({}) do |(el, i), result|
  result[el] = path_arr[i] if el.is_a?(Symbol)
end

2019-03-28 16:38 UTC, iBublik commented on lib/simpler/router/route.rb
> +      def size_eql?(path1, path2)
Зачем это в метод выносить?

2019-03-28 16:38 UTC, iBublik commented on lib/simpler/view.rb
> +      when :plain
Будет больше форматов 100%. Неудобно через case их обрабатывать, лучше через send

2019-03-29 06:38 UTC, arbaev commented on lib/middleware/racklogger.rb
> +    @logger.close
Почему? Наверно, правильнее сказать "это _можно_ не делать".
Если только по условию app.log — наш единоличный файл, то да. Но даже в этом случае, закрытие лога не помешает.

2019-03-29 06:52 UTC, arbaev commented on lib/simpler/controller.rb
> +      @request.env['simpler.template'] = {}
Да, такая ситуация есть, когда рендер дефолтного шаблона, template == nil
И мне вообще не нравится, что template может быть nil, строкой и хешем.

2019-03-29 10:27 UTC, iBublik commented on lib/middleware/racklogger.rb
> +    @logger.close
https://stackoverflow.com/a/48063335

2019-03-29 10:28 UTC, iBublik commented on lib/simpler/controller.rb
> +      @request.env['simpler.template'] = {}
Согласен, можно привести к единообразию, достаточно метод `render` доработать

2019-03-29 16:09 UTC, iBublik approved these changes

2019-03-29 16:09 UTC, iBublik commented on lib/simpler/controller.rb
> +                 elsif template.nil?
Вот это довольно странно. Ты думаешь кто-то будет писать `render nil`?

2019-03-29 16:09 UTC, iBublik commented on lib/simpler/controller.rb
> +                 elsif template.nil?
Лучше уж сделать дефолтным параметром то что у тебя сейчас подставляется, когда template nil

2019-03-29 16:09 UTC, iBublik commented on lib/simpler/router/route.rb
> +        pattern.zip(path_arr).all? do |el|
Сделай `all? do |path_part, pattern_part|`, чтоб не оперировать непонятными first/last

2019-03-30 06:03 UTC, merged